/*
 * generated by Xtext 2.13.0
 */
package com.rainerschuster.xtext.langserver.fidl.tests

import com.google.inject.Inject
import com.rainerschuster.xtext.langserver.fidl.fIDL.File
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(FIDLInjectorProvider)
class FIDLParsingTest {
	@Inject
	ParseHelper<File> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
