/*
 * generated by Xtext 2.12.0
 */
package com.rainerschuster.xtext.langserver.fidl.tests

import com.google.inject.Inject
import com.rainerschuster.xtext.langserver.fidl.fIDL.File
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(FIDLInjectorProvider)
class FIDLParsingTest {
	@Inject
	ParseHelper<File> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
