/*
 * generated by Xtext 2.12.0
 */
package com.rainerschuster.xtext.langserver.fidl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FIDLStandaloneSetup extends FIDLStandaloneSetupGenerated {

	def static void doSetup() {
		new FIDLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
